### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zenfone-xdavn** [zenfone-legacy/android_device_asus_T00F#1]
Hello I use device T00F of you error gralloc.h use of old-style cast , although you fix it

**Comment by Flex1911** [comment]
Fixed with 1a2a2e233885f5a16597284b5eea821fef9800cf, just update your tree

**Comment by Flex1911** [comment]
Fixed with 1a2a2e233885f5a16597284b5eea821fef9800cf, just update your tree

**Comment by zenfone-xdavn** [comment]
oke thanks
